name: Interactive HTML Bom GitHub Pages Deploy

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v2.3.4
    
    - name: Clone InteractiveHTMLBom
      uses: actions/checkout@v2.3.4
      with:
        repository: openscopeproject/InteractiveHtmlBom
        path: ./InteractiveHtmlBom
         
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
        
    #- name: Install dependencies
    #  run: pip install wxpython
      
    - name: Build bom
      run: python3 .InteractiveHtmlBom/generate_interactive_bom.py ./Proton/Proton.kicad_pcb
      
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
